### PR TITLE
Update airplay.js

### PR DESCRIPTION
**Pull request by jimmywarting**
You misspelled `originalNode`

Clicking the airplay btn don't make it "start" so sending the event there seems wrong
instead i listen on airplay change event and look if it's currently casting

This fixes it...

A nice addition would be to have some indication that it's currently playing on airplay like on/off icon
Sidenote: the icon is to far up

skarmavbild 2017-04-22 kl 21 21 19

### CODE REVIEW

**Comment by rafa8626** [comment]
Thanks. PR merged

**Comment by rafa8626** [comment]
BTW I fixed the icon CSS. I'll check what can be done for the icon off/on

**Comment by jimmywarting** [comment]
I think it looks good if both airplay and chromecast icon use the color `#66A8CC` when it's beeing active

**Comment by rafa8626** [comment]
Yeah I agree. I'll rename the class and set the styles to match this approach. Thanks for pointing this

**Pull request merged**
