### PR TITLE
Add snapshot plugin

### PR DESCRIPTION
**Pull request by Qoraiche**

### CODE REVIEW

**Comment by Qoraiche** [comment]
@berryamin I don't those lines just

**Comment by Qoraiche** [comment]
@berryamin so are this gonna be merged?

**Comment by Qoraiche** [comment]
@berryamin any news about this PR?

**Comment by berryamin** [comment]
@Qoraiche : I was waiting for someone to volunteer as a maintainers for the plugins .. but #152 is opened since 2 weeks and no one has applied. Ok let's write John Dyer, I'll take over this role and merge the stagging PR asap :-)

**Comment by berryamin** [comment]
@Qoraiche : I was waiting for someone to volunteer as a maintainers for the plugins .. but #152 is opened since 2 weeks and no one has applied. Ok let's write John Dyer, I'll take over this role and merge the stagging PR asap :-)

**Pull request merged**
