### PR TITLE
Plugin to allow locking of playback controls

### PR DESCRIPTION
**Pull request by jhutchins**

### CODE REVIEW

**Comment by rafa8626** [comment]
Thanks for the PR; I have tested it and I found out that it doesn't work as expected. You are registering only one button (lock) which is correct; I'd suggest you to rather than using an unlock button, try to set different attributes and classes for the already generated lock button. Otherwise, when I click the lock I'll see the changes. Documentation is good. I'll need you to fix this so I can give a second test and merge.

**Comment by jhutchins** [comment]
The reason it wasn't working was a bug in the plugin fixed in 0ea1c03fa8ad40a3fd8880cc2676fb25aaa1661a and a bug in the player fixed by https://github.com/mediaelement/mediaelement/pull/2254. With those in place I think you'll find much better results.

**Comment by rafa8626** [comment]
Ok I'll check this in a minute. Thanks

**Comment by rafa8626** [comment]
OK I have tested it and when I click the lock icon, the control bar disappears completely and it doesn't come back. How do you unlock? Because I have clicked the play button and other areas and I can't figure out how is it supposed to be unlocked

**Comment by rafa8626** [comment]
I think I know why you have this issue: I think there are some styles missing. Let me check that and if it's just that, I'll add them and merge this

**Comment by rafa8626** [comment]
OK I see the button now. However, I'll strongly advise to put something else to display the unlock button when the media hasn't started to play yet. That's why I was having issues to understand how it worked. Once you play and lock it I see the button. But if you click the lock button you should see the unlock button immediately, and I had to click on the player to see it. So, in order for me to merge this:
1) Make sure you can't lock when media is not playing
2) Make sure unlock button is visible once you click lock button
3) Tooltip for unlock MUST indicate how many times you need to click it to unlock experience

**Comment by rafa8626** [comment]
Any updates on this? Currently it has a conflict and needs to address the issues stated above.

**Comment by rafa8626** [comment]
Any updates on this?

**Comment by rafa8626** [comment]
Closing this PR since no updates have been posted. If you want this to be merged, please follow the indications above and solve the conflicts

**Pull request closed without merging**
