### PR TITLE
Updated source chooser to work natively with hls

### PR DESCRIPTION
**Pull request by Spartanace1024**
- Added startingSource option which is necessary when starting source chooser on hls stream. If this property is not set url will show up as blob.
- Added displayType variable which will allow users to turn on or off displaying video type next to stream title.
- hlsvideo will be seamlessly transitioned to when switching between different types of streams.

 _Known issues source video type must be set to application/x-mpegURL when specifying a hls video format._

### CODE REVIEW

**Comment by rafa8626** [comment]
Please do your changes on the `src` folder only not in the `dist` folder so I can review easily please

**Comment by Spartanace1024** [comment]
You got it I will go ahead and do so from now on

**Comment by rafa8626** [comment]
Should I close this PR so you can submit a new one with changes only in src folder?

**Comment by Spartanace1024** [comment]
Yeah that works. I'm a bit pressed for time this coming week but I'll be sure to send it in the src folder as soon as I have the chance!

**Comment by rafa8626** [comment]
Sounds good. Thanks and I'll review this when you are ready

**Pull request closed without merging**
