### PR TITLE
Google Tag Manager added

### PR DESCRIPTION
**Pull request by isantolin**
I added support for Google Tag Manager

### CODE REVIEW

**Comment by rafa8626** [comment]
Thanks for the PR. As a quick request, add a doc page for the plugin so I can review it completely

**Comment by isantolin** [comment]
@rafa8626 OK! i Will do on weekend

**Comment by rafa8626** [comment]
PR merged. Thanks

**Comment by KZeni** [comment]
Is there any reason this isn't currently as part of the dist folder? Seems odd it's just in source while all others are then also in dist (which I'm guessing is what https://cdnjs.com/libraries/mediaelement-plugins & others are looking at so GTM is currently not readily available via a CDN due to what appears to be an oversight(?)

**Pull request merged**
